#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.3f1_393bae82dbb8"
#define UNITY_VERSION_FULL_NICE "2018.3.3f1 (393bae82dbb8)"
#define UNITY_VERSION_BLD 3750830
#define UNITY_VERSION_DATE 1548267374
#define UNITY_VERSION_WIN "2018.3.3.3750830"
#define UNITY_VERSION_BRANCH "2018.3/staging"
