#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2018.3.3f1"
#define UNITY_VERSION_DIGITS "2018.3.3"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2018
#define UNITY_VERSION_MAJ 3
#define UNITY_VERSION_MIN 3
#define UNITY_IS_BETA 0
